/**
 * Operational Activity & Audit Trail Action Constants
 */

export const ACTIVITY_ACTION = {
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  EMPLOYEE_STATUS_CHANGED: 'EMPLOYEE_STATUS_CHANGED',
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',
  DEPARTMENT_STATUS_CHANGED: 'DEPARTMENT_STATUS_CHANGED',
  ATTENDANCE_CHECKED_IN: 'ATTENDANCE_CHECKED_IN',
  ATTENDANCE_CHECKED_OUT: 'ATTENDANCE_CHECKED_OUT',
  LEAVE_SUBMITTED: 'LEAVE_SUBMITTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_ARCHIVED: 'DOCUMENT_ARCHIVED',
  ANNOUNCEMENT_CREATED: 'ANNOUNCEMENT_CREATED',
  ANNOUNCEMENT_PUBLISHED: 'ANNOUNCEMENT_PUBLISHED',
  ANNOUNCEMENT_ARCHIVED: 'ANNOUNCEMENT_ARCHIVED',
  AI_TASK_SUMMARY: 'AI_TASK_SUMMARY',
  AI_LEAVE_DRAFT: 'AI_LEAVE_DRAFT',
  AI_DOCUMENT_SUMMARY: 'AI_DOCUMENT_SUMMARY',
  AI_PRODUCTIVITY_INSIGHT: 'AI_PRODUCTIVITY_INSIGHT',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PREFERENCES_UPDATED: 'PREFERENCES_UPDATED',
};

export const ACTIVITY_ACTION_LIST = Object.values(ACTIVITY_ACTION);

export const ACTIVITY_ENTITY_TYPE = {
  EMPLOYEE: 'Employee',
  DEPARTMENT: 'Department',
  ATTENDANCE: 'Attendance',
  LEAVE: 'Leave',
  TASK: 'Task',
  DOCUMENT: 'Document',
  ANNOUNCEMENT: 'Announcement',
  ANALYTICS: 'Analytics',
  PROFILE: 'Profile',
  USER: 'User',
};

export const ACTIVITY_ENTITY_TYPE_LIST = Object.values(ACTIVITY_ENTITY_TYPE);
