/**
 * In-App Notification Constants & Types
 */

export const NOTIFICATION_TYPE = {
  LEAVE_SUBMITTED: 'LEAVE_SUBMITTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  DOCUMENT_ADDED: 'DOCUMENT_ADDED',
  ANNOUNCEMENT_PUBLISHED: 'ANNOUNCEMENT_PUBLISHED',
  ATTENDANCE_REMINDER: 'ATTENDANCE_REMINDER',
};

export const NOTIFICATION_TYPE_LIST = Object.values(NOTIFICATION_TYPE);

export const NOTIFICATION_ENTITY_TYPE = {
  LEAVE: 'Leave',
  TASK: 'Task',
  DOCUMENT: 'Document',
  ANNOUNCEMENT: 'Announcement',
  ATTENDANCE: 'Attendance',
  USER: 'User',
  DEPARTMENT: 'Department',
};

export const NOTIFICATION_ENTITY_TYPE_LIST = Object.values(NOTIFICATION_ENTITY_TYPE);
